FROM python:3.11
WORKDIR /server
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    libldap2-dev libsasl2-dev libpq-dev lcov valgrind && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
COPY . .

RUN pip install --no-cache-dir poetry
ENV POETRY_VIRTUALENVS_CREATE=false

COPY pyproject.toml poetry.lock* ./

RUN poetry lock

COPY README.md ./

RUN poetry install --no-root
RUN apt-get update -y && apt-get install -y --no-install-recommends figlet && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . .

CMD ["uvicorn", "main:server", "--host", "0.0.0.0", "--port", "5000"]
